### ISSUE TITLE
后台 返回的 json 轮播 只有 一张图时  让下面的 指示器 不显示

### ISSUE THREAD

**Issue by scaPEGoatno** [H07000223/FlycoBanner_Master#1]
怎么办?

**Comment by H07000223** [comment]
这个属性我在写这个Lib的时候考虑了下~最后没加~
你可以通过setIndicatorShow解决,如下:
           sib
                .setSource(DataProvider.getList())
                .setIndicatorShow(DataProvider.getList().size() > 1)
                .startScroll();
