### ISSUE TITLE
持有 Context 引用是不是造成内存泄露了

### ISSUE THREAD

**Issue by Ivolian** [H07000223/FlycoBanner_Master#10]
BaseBanner 里
protected Context context;

**Comment by H07000223** [comment]
应该不会~不放心的话你可以离开banner所在页面时调用pauseScroll()停止轮播
回到banner所在页面时调用 goOnScroll()继续

**Comment by Ivolian** [comment]
比如我用一个 Actvitiy 的地址作为 Context 传入 Banner，直到该 Activity destory 时，Banner 一直持有该 Activity 的引用。
我用了 leakcanary 库，https://github.com/square/leakcanary，它提醒我有内存泄露的问题。

**Comment by H07000223** [comment]
LeakCanary这样提醒应该有他的道理~这个context不是直接传入的而是取自Banner构造方法中,如果有问题的话那么所有自定义控件都有可能存在这个问题,就你说的这个我目前也不知道怎么改😂

**Comment by Ivolian** [comment]
也许，只要将这个成员变量删掉，在需要使用 context 的地方调用 this.getContext()
