### ISSUE TITLE
Crash When I Update ArrayList My Gallaries

### ISSUE THREAD

**Issue by trihung93** [H07000223/FlycoBanner_Master#12]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 7, found: 5 Pager id: ffffffff Pager class: class com.flyco.banner.widget.LoopViewPager.LoopViewPager Problematic adapter: class com.flyco.banner.widget.LoopViewPager.LoopPagerAdapterWrapper

**Comment by H07000223** [comment]
fix it in the newest Version 2.0.0
