### ISSUE TITLE
如何实现类似于Gallery效果，viewpager可以显示多张图效果

### ISSUE THREAD

**Issue by android12345** [H07000223/FlycoBanner_Master#2]
首先，这个库真的很牛，但是我遇到一个问题我将banner的 android:clipChildren="false"，android:layerType="software"，viewpager也设置 android:clipChildren="false" ，但是还不能出现gallery效果，求指点

**Comment by H07000223** [comment]
本库目前不支持~想实现ViewPager一屏多图请参照http://www.trinea.cn/android/viewpager-multi-fragment-effect/
