### ISSUE TITLE
内存泄露问题

### ISSUE THREAD

**Issue by vipheyue** [H07000223/FlycoBanner_Master#31]
![3641756e-6de4-42fc-b1a3-580cb2a3a1ff](https://cloud.githubusercontent.com/assets/11717882/19883341/c44ac73e-a04e-11e6-820c-6192483c3da8.png)
你可以看一下 我可以提供更多日志 vipheyue@foxmail.com

**Comment by vipheyue** [comment]
一直在轮循?

**Comment by H07000223** [comment]
1.可以参考[issue25](https://github.com/H07000223/FlycoBanner_Master/issues/25)
2.实在不行，可以尝试别的开源库
