### ISSUE TITLE
当该控件嵌套在listview中，存在viewpage横向滑动与listview的冲突

### ISSUE THREAD

**Issue by caprice** [H07000223/FlycoBanner_Master#4]

**Comment by H07000223** [comment]
你是怎么嵌套~我是放在Header里面~并没有你说的那样~

**Comment by caprice** [comment]
我是放在recyclerview中的header中里面的，listview没试过。我以为是常见的listview与viewpager冲突的原因，你帮忙看下

**Comment by H07000223** [comment]
RecyclerView我没怎么用过哦...我得试试再说~

**Comment by caprice** [comment]
重新更新下，我切换到listview还是一样，并不是不能手动左右滑动，而是滑动时候很费力。另外我是放在下拉刷新里面的，我也试过如果单纯listview里面加个header是不会有问题的。因此应该问题应该是放在下拉刷新与横向滑动冲突的问题。

**Comment by H07000223** [comment]
额~你用的什么刷新控件,我用的是PullToRefresh没问题~https://github.com/chrisbanes/Android-PullToRefresh
这个冲突问题~自行百度谷歌.可能要改造ListView或者要改造我的Banner库处理手势冲突~

**Comment by caprice** [comment]
我用的这个android-Ultra-Pull-To-Refresh https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh，恩嗯，多谢指教！

**Comment by H07000223** [comment]
我用android-Ultra-Pull-To-Refresh库试过了~的确会这样~我去看了他的issue也有类似的提问,里面有解决方案但是我没试过~你可以借鉴下~

**Comment by caprice** [comment]
多谢！我也已经看过里面的解决方案了。差不多可以了。

**Comment by H07000223** [comment]
小case~问题能解决就好~
