### ISSUE TITLE
在6.0上图片显示无法全屏显示

### ISSUE THREAD

**Issue by wl386123298** [H07000223/FlycoBanner_Master#6]
在6.0上图片轮播显示貌似有个padding，在4.x上ok！不知为何

**Comment by H07000223** [comment]
你先用我的Demo试试,对比下Demo的写法.

**Comment by wl386123298** [comment]
demo在6.0上都是ok的，但是为何根据你的写法，在真机的项目中，图片的展示都有个padding的存在，很是奇怪，我也设置了imageview的scaleType为fixed_xy,但是还是有个padding！

**Comment by H07000223** [comment]
既然Demo是ok,应该是你哪边设置不对吧~
1.关于bb_scale(实际图片宽高比)有没有设置
2.关于ImageView,有没有如下设置宽高
```java
        int itemWidth = dm.widthPixels;//屏幕宽度
        int itemHeight = (int) (itemWidth * 360 * 1.0f / 640);//360/640图片实际比例
        iv.setScaleType(ImageView.ScaleType.CENTER_CROP);//设置为CENTER_CROP
        iv.setLayoutParams(new LinearLayout.LayoutParams(itemWidth, itemHeight));
```

**Comment by wl386123298** [comment]
View inflate = View.inflate(context, R.layout.adapter_simple_image, null);
        ImageView iv = (ImageView) inflate.findViewById(R.id.iv);

        int itemWidth = dm.widthPixels;
        LogUtils.i(itemWidth);
        int itemHeight = DensityUtil.dip2px(context, 120);
        iv.setScaleType(ImageView.ScaleType.FIT_XY);
        iv.setLayoutParams(new LinearLayout.LayoutParams(itemWidth, itemHeight));

**Comment by wl386123298** [comment]
View inflate = View.inflate(context, R.layout.adapter_simple_image, null);
   ImageView iv = (ImageView) inflate.findViewById(R.id.iv);
   int itemWidth = dm.widthPixels;
   int itemHeight = DensityUtil.dip2px(context, 120);
   iv.setLayoutParams(new LinearLayout.LayoutParams(itemWidth, itemHeight));
Glide.with(context).load(list.get(position).getImageUrl()).placeholder(R.drawable.icon_default_load_image).into(iv);
