### ISSUE TITLE
后台 返回的 json 轮播 只有 一张图时， 无法禁止手指滑动图片

### ISSUE THREAD

**Issue by chasel** [H07000223/FlycoBanner_Master#7]
不让Indicator和不让滚动都可以通过属性做到， 但是唯独没有看到禁止用手去滑动该图片的事件啊， 就是说还是可以滑动， 由办法能解决这个问题吗？

**Comment by H07000223** [comment]
这功能暂时没有,当初写的时候也没考虑~这个你可以自行Google,类似于'viewpager 禁止滚动'

**Comment by chasel** [comment]
能否告诉， 你图片的高度算法是什么
itemWidth * 360 * 1.0f / 640
这个和bb_scale属性有什么关联， 
比如我现在高度想变成170px， 这个计算方法是什么

**Comment by H07000223** [comment]
Demo中图片原始宽高640*360,根据图片比例和手机屏宽计算出高度,从而保证图片显示的正确性,不会被过多裁剪或者变形.
你想要170px的话~可以在设置xml中设置Banner高度170px,在代码设置下ImageView的高度为170px就可以了
