### ISSUE TITLE
后台返回的 json一张图时，无法禁止手指滑动图片, 需自定义ViewPager才能达到目的

### ISSUE THREAD

**Issue by chasel** [H07000223/FlycoBanner_Master#8]
我只能想到通过控制View事件转发机制才能做到， 但是这个需要自定义重写ViewPager类， 能否提供一个可以使用自定义ViewPager的方法， 或者提交一个我自己修改后的PR？
或者有其它办法？

**Comment by H07000223** [comment]
copy一份源码~然后自己倒腾~

**Comment by chasel** [comment]
ok
